set_property PACKAGE_PIN N18 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]


set_property PACKAGE_PIN U20 [get_ports hsync]
set_property PACKAGE_PIN V20 [get_ports vsync]
set_property PACKAGE_PIN P20 [get_ports {rgb_data[15]}]
set_property PACKAGE_PIN M17 [get_ports {rgb_data[14]}]
set_property PACKAGE_PIN N20 [get_ports {rgb_data[13]}]
set_property PACKAGE_PIN M20 [get_ports {rgb_data[12]}]
set_property PACKAGE_PIN M18 [get_ports {rgb_data[11]}]
set_property PACKAGE_PIN L17 [get_ports {rgb_data[10]}]
set_property PACKAGE_PIN L20 [get_ports {rgb_data[9]}]
set_property PACKAGE_PIN U19 [get_ports {rgb_data[8]}]
set_property PACKAGE_PIN T19 [get_ports {rgb_data[7]}]
set_property PACKAGE_PIN T20 [get_ports {rgb_data[6]}]
set_property PACKAGE_PIN R19 [get_ports {rgb_data[5]}]
set_property PACKAGE_PIN P19 [get_ports {rgb_data[4]}]
set_property PACKAGE_PIN R18 [get_ports {rgb_data[3]}]
set_property PACKAGE_PIN N17 [get_ports {rgb_data[2]}]
set_property PACKAGE_PIN P18 [get_ports {rgb_data[1]}]
set_property PACKAGE_PIN M19 [get_ports {rgb_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]





##### Cameraa

set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports camera_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports camera_hs]
set_property IOSTANDARD LVCMOS33 [get_ports camera_led]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports camera_vs]
set_property IOSTANDARD LVCMOS33 [get_ports camera_xclk]
set_property PACKAGE_PIN D19 [get_ports {camera_data[7]}]
set_property PACKAGE_PIN H18 [get_ports {camera_data[6]}]
set_property PACKAGE_PIN D18 [get_ports {camera_data[5]}]
set_property PACKAGE_PIN D20 [get_ports {camera_data[4]}]
set_property PACKAGE_PIN H17 [get_ports {camera_data[3]}]
set_property PACKAGE_PIN C20 [get_ports {camera_data[2]}]
set_property PACKAGE_PIN B19 [get_ports {camera_data[1]}]
set_property PACKAGE_PIN B20 [get_ports {camera_data[0]}]
set_property PACKAGE_PIN E19 [get_ports camera_pclk]
set_property PACKAGE_PIN F19 [get_ports camera_hs]
set_property PACKAGE_PIN K17 [get_ports camera_vs]
set_property PACKAGE_PIN F20 [get_ports camera_xclk]
set_property PACKAGE_PIN J18 [get_ports scl]
set_property PACKAGE_PIN G20 [get_ports sda]
set_property PACKAGE_PIN H16 [get_ports camera_led]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets camera_pclk_IBUF]


